<?php
/**
 * @file
 * Hook implementations and callbacks for the Macho Man solution pack.
 */

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_solution_pack_macho_man_islandora_required_objects(IslandoraTuque $connection) {
  // Path to this module.
  $module_path = drupal_get_path('module', 'islandora_solution_pack_macho_man');

  // Macho Man collection.
  $macho_man_collection = $connection->repository->constructObject('machoman:collection');
  $macho_man_collection->owner = 'fedoraAdmin';
  $macho_man_collection->label = 'Macho Man Collection';
  $macho_man_collection->models = 'islandora:collectionCModel';
  $macho_man_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  // TN datastream.
  $ds = $macho_man_collection->constructDatastream('TN', 'M');
  $ds->label = 'Thumbnail';
  $ds->mimetype = 'image/gif';
  $ds->setContentFromFile("$module_path/data/thumb.gif", FALSE);
  $macho_man_collection->ingestDatastream($ds);

  // Macho man collection policy.
  $macho_man_collection_policy = $macho_man_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $macho_man_collection_policy->label = 'Collection policy';
  $macho_man_collection_policy->mimetype = 'application/xml';
  $macho_man_collection_policy->setContentFromFile("$module_path/xml/macho_man_collection_policy.xml", FALSE);
  $macho_man_collection->ingestDatastream($macho_man_collection_policy);
  return array(
    'islandora_solution_pack_macho_man' => array(
      'title' => 'Islandora Macho Man',
      'objects' => array(
        $macho_man_collection,
      ),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function islandora_solution_pack_macho_man_views_api($module = NULL, $api = NULL) {
  return array(
    "api" => '3.0',
    'path' => drupal_get_path('module', 'islandora_solution_pack_macho_man') . '/views',
  );
}
